# Site settings
title: Pranav Garg
email: pranavgarg@gmail.com
url: pranavgarg.in
description: "Ai enthusiast who survives on a healthy diet of Research papers"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Pranav Garg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pgtgrly
  - title: linkedin
    url: https://in.linkedin.com/in/pranavgarg1997
  - title: github
    url: https://github.com/pgtgrly
# Build settings
markdown: kramdown
permalink: pretty
